### ISSUE TITLE
Crash when trying to access crash report

### ISSUE THREAD

**Issue by refola** [FunkyMuse/Vigilante#100]
My first crash report in the app crashes the app when I try opening it. Here's the (working!) crash report from trying to open the first crash report.

I suspect that the first crash report is from too many "plugged in" and "unplugged" events logged; this phone's charger port is starting to fail, resulting in several nominal (un)plug events per second until I set it down at the correct angle and cable tension.

```
----------- Stacktrace -----------

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 18051304 bytes
	at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:106)
	at i.s.m.g(Unknown Source:31)
	at com.crazylegend.vigilante.crashes.CrashFragment$c.a(:1)
	at d.a.f.b.onClick(:11)
	at android.view.View.performClick(View.java:6597)
	at android.view.View.performClickInternal(View.java:6574)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25906)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.os.TransactionTooLargeException: data parcel size 18051304 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:1129)
	at android.content.IClipboard$Stub$Proxy.setPrimaryClip(IClipboard.java:183)
	at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:104)
	... 14 more


----------- END of stacktrace -----------

``````````` Thread info ```````````

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 6
Thread time: 0 hr 0 min, 2 sec

``````````` END of thread info ```````````

----------- Device info -----------

Report ID: 0531b9c1-9152-4cc2-a83d-1c2b129c4258
Device ID: 0879c13eb34cc597
Application version: 8
Default launcher: com.android.launcher3
Timezone name: Mountain Standard Time
Timezone ID: America/Phoenix
Version release: 9
Version incremental : 8582edc3f1
Version SDK: 28
Board: MSM8974
Bootloader: unknown
Brand: oneplus
CPU_ABIS_32: armeabi-v7a, armeabi
CPU_ABIS_64: N/A
Supported ABIS: armeabi-v7a, armeabi
Device: A0001
Display: lineage_bacon-userdebug 9 PQ3A.190801.002 8582edc3f1
Fingerprint: oneplus/bacon/A0001:5.0.2/LRX22G/YNG1TAS0YL:user/release-keys
Hardware: bacon
Host: lineage-buildkite
ID: PQ3A.190801.002
Manufacturer: OnePlus
Product: bacon
Build time: 1595472138000
Build time formatted: 22-07-2020 19:42:18
Type: userdebug
Radio: DI.3.0.c6-00241-M8974AAAAANAZM-1
Tags: release-keys
User: buildkite-agent
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: N/A
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 59
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm MSM8974PRO-AC
Revision	: 0000
Serial		: 0000000000000000
# of CPU cores: 4
Up time with sleep: 242 hr 45 min, 48 sec
Up time without sleep: 76 hr 11 min, 42 sec

----------- END of Device info -----------

########### Exit reasons ###########
N/A
########### END of exit reasons ###########

*********** Application info ***********

App name: Vigilante
Version code: 8
Version name: 1.0.9
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 31-12-2020 08:03:54
Last updated: 14-01-2021 16:56:34
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE
Default prefs: pref_dot = true, pref_bypass_dnd = false, Locale.Helper.Selected.Language = en, pref_language = en, pref_notifications = true, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = false

*********** END of Application info ***********


^^^^^^^^^^^ Currently running foreground/background processes ^^^^^^^^^^^

N/A

^^^^^^^^^^^ END of running foreground/background processes info ^^^^^^^^^^^
```

**Comment by FunkyMuse** [comment]
This did happen once you clicked on the crash right?

**Comment by refola** [comment]
Correct. This happens every time I tap on crash report 1.
