### ISSUE TITLE
Vigilante keeps closing with OpenLauncher

### ISSUE THREAD

**Issue by X01011010X** [FunkyMuse/Vigilante#131]
Hey,

first off all: great app. I've been using it for quite a while. I was using Microsoft Launcher during the whole time and now switched to an FOSS launcher called [OpenLauncher](https://f-droid.org/de/packages/com.benny.openlauncher/). Now Vigilante will not work (it does not show me, when the microphone or the camera is used (e.g. when I start a video recording) and after a while I get the messagte that the app keeps shutting down and that I need to close it.

Any ideas, why this is happening. It is still working with the other launcher by Microsoft.

Best regards,

XZX

**Comment by FunkyMuse** [comment]
Hello,

If you get a crash in Vigilante then please report it, otherwise it's a launcher problem.

You can go into the bug icon, tap onto a crash and it'll open an issue here automatically all you need to do is paste the crash log

**Comment by X01011010X** [comment]
Wow, thanks for the ultra-fast reply. In the meantime I tried something different. I just resetted the app and now it is working again. I do not know what it was, because it started once I started using the other launcher. To prevent the problem/identify it, here's the latest crash report I copied before resetting the app.

----------- Stacktrace -----------

java.lang.NullPointerException: Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference
	at android.os.Parcel.createException(Parcel.java:2077)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.accessibilityservice.IAccessibilityServiceConnection$Stub$Proxy.findAccessibilityNodeInfoByAccessibilityId(IAccessibilityServiceConnection.java:705)
	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:346)
	at android.view.accessibility.AccessibilityRecord.getSource(AccessibilityRecord.java:189)
	at com.crazylegend.vigilante.service.VigilanteService.onAccessibilityEvent(:6)
	at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:1635)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1824)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.appwidget.AppWidgetServiceImpl$AppWidgetManagerLocal.getHostedWidgetPackages(AppWidgetServiceImpl.java:4808)
	at com.android.server.accessibility.AccessibilityManagerService$SecurityPolicy.computeValidReportedPackages(AccessibilityManagerService.java:3387)
	at com.android.server.accessibility.AbstractAccessibilityServiceConnection.findAccessibilityNodeInfoByAccessibilityId(AbstractAccessibilityServiceConnection.java:596)
	at android.accessibilityservice.IAccessibilityServiceConnection$Stub.onTransact(IAccessibilityServiceConnection.java:312)
	at android.os.Binder.execTransactInternal(Binder.java:1021)



----------- END of stacktrace -----------

``````````` Thread info ```````````

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 17
Thread time: 0 hr 0 min, 1 sec

``````````` END of thread info ```````````

----------- Device info -----------

Report ID: e597e252-956f-4873-b17e-0b18b0a8022e
Device ID: d92641c7a07318ed
Application version: 8
Default launcher: com.microsoft.launcher
Timezone name: Central European Standard Time
Timezone ID: Europe/Berlin
Version release: 10
Version incremental : 00WW_4_16E
Version SDK: 29
Board: SDM636
Bootloader: unknown
Brand: Nokia
CPU_ABIS_32: armeabi-v7a, armeabi
CPU_ABIS_64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: CTL_sprout
Display: 00WW_4_16E
Fingerprint: Nokia/Crystal_00WW/CTL_sprout:10/QKQ1.190828.002/00WW_4_16E:user/release-keys
Hardware: qcom
Host: cm-build-40-18
ID: QKQ1.190828.002
Manufacturer: HMD Global
Product: Crystal_00WW
Build time: 1609234794000
Build time formatted: 29-12-2020 10:39:54
Type: user
Radio: MPSS.AT.3.1-00822_GEN_PACK-1.245278.1.262738.2
Tags: release-keys
User: cm
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 61
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc SDM636
# of CPU cores: 8
Up time with sleep: 9 hr 1 min, 31 sec
Up time without sleep: 3 hr 23 min, 56 sec

----------- END of Device info -----------

########### Exit reasons ###########
N/A
########### END of exit reasons ###########

*********** Application info ***********

App name: Vigilante
Version code: 8
Version name: 1.0.9
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 22-01-2021 06:04:16
Last updated: 22-01-2021 06:04:16
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE
Default prefs: pref_dot = true, pref_exclude_vigilante_from_notifications = true, pref_bypass_dnd = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_notifications = true, pref_biometric_auth = true

*********** END of Application info ***********


^^^^^^^^^^^ Currently running foreground/background processes ^^^^^^^^^^^


com.crazylegend.vigilante.service.VigilanteService

^^^^^^^^^^^ END of running foreground/background processes info ^^^^^^^^^^^

**Comment by FunkyMuse** [comment]
Was the app running when you changed the launcher?

**Comment by X01011010X** [comment]
Yes, it was running in the background, but was not open. Once I got the crash message, I stopped the app (in the new launcher) and tried to restart it several times with this OpenLauncher as the default launcher. But it just kept on crushing. After resetting it, everything is working fine again. By the way: in the end it kept on crushing on Microsoft Launcher, too. So maybe the switching really messed something up and now it is working again. But I never had this problem with Vigilante when switching between different launchers before, to be honest.

**Comment by FunkyMuse** [comment]
From the crash i can see that's an issue on the Android side of things, it's weird since the crash says it's crashing when the event is given from Android system but the crash indicates that the system is crashing hence the app, weird

**Comment by X01011010X** [comment]
So, it's like a loop? Weird. I have no experience in coding, so I cannot read the crash report. Maybe it is just a one-time thing and maybe it had nothing to do with OpenLauncher in the first place (which is otherwise running perfectly fine). I just wanted to let you know. I'm just glad, everything is working again. :)

**Comment by FunkyMuse** [comment]
If it's one time it could've been a system hiccup, i will close the issue now, glad that everything is working fine.
