### ISSUE TITLE
App crash on selecting unnamed notification entry in log

### ISSUE THREAD

**Issue by Jenneke42** [FunkyMuse/Vigilante#133]
----------- Stacktrace -----------

android.content.pm.PackageManager$NameNotFoundException: ml.docilealligator.infinityforreddit
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:423)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:412)
	at d.a.a.b.a.a(Unknown Source:15)
	at com.crazylegend.vigilante.notifications.details.NotificationDetailsFragment$d$a.t(:17)
	at com.crazylegend.vigilante.notifications.details.NotificationDetailsFragment$d$a.l(:2)
	at h.a.m2.t.t(Unknown Source:59)
	at h.a.m2.t.k(:2)
	at h.a.m2.t0.j$a$a$b.t(:2)
	at h.a.m2.t0.j$a$a$b.l(:2)
	at h.a.b.s0(:5)
	at d.d.a.i.X(:2)
	at h.a.m2.t0.j$a$a.a(Unknown Source:121)
	at h.a.m2.o0.c(:15)
	at h.a.m2.o0$a.t(Unknown Source:12)
	at l.o.j.a.a.s(:2)
	at d.d.a.i.i0(Unknown Source:40)
	at h.a.k.q(:6)
	at h.a.k.y(Unknown Source:30)
	at h.a.k.s(:3)
	at h.a.m2.o0.e(:7)
	at h.a.m2.o0.a(:1)
	at h.a.m2.t0.s$a.k(:1)
	at h.a.m2.t0.r.v(:22)
	at h.a.m2.t0.r.a(Unknown Source:0)
	at d.a.e.b.a.t(:3)
	at l.o.j.a.a.s(:2)
	at h.a.o0.run(Unknown Source:72)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

----------- END of stacktrace -----------

``````````` Thread info ```````````

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 21
Thread time: 0 hr 4 min, 56 sec

``````````` END of thread info ```````````

----------- Device info -----------

Report ID: a3e7ddaf-9aa1-45fd-867e-54b367884a3b
Device ID: 5bd8fde1540af4d3
Application version: 8
Default launcher: com.teslacoilsw.launcher
Timezone name: Pacific Standard Time
Timezone ID: America/Los_Angeles
Version release: 11
Version incremental : 7038034
Version SDK: 30
Board: sunfish
Bootloader: s5-0.3-6835615
Brand: google
CPU_ABIS_32: armeabi-v7a, armeabi
CPU_ABIS_64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: sunfish
Display: RQ1A.210205.004
Fingerprint: google/sunfish/sunfish:11/RQ1A.210205.004/7038034:user/release-keys
Hardware: sunfish
Host: abfarm805
ID: RQ1A.210205.004
Manufacturer: Google
Product: sunfish
Build time: 1608168918000
Build time formatted: 16-12-2020 17:35:18
Type: user
Radio: g7150-00023-201008-B-6891498
Tags: release-keys
User: android-build
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 79
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc SDMMAGPIE
# of CPU cores: 8
Up time with sleep: 13 hr 24 min, 53 sec
Up time without sleep: 6 hr 5 min, 26 sec

----------- END of Device info -----------

########### Exit reasons ###########

~~~~~~~~~~~ Exit reason #1 ~~~~~~~~~~~

Description: crash
Importance: SERVICE
Reason: CRASH
Timestamp: 22-02-2021 08:37:58

~~~~~~~~~~~ END of exit reason #1 ~~~~~~~~~~~


########### END of exit reasons ###########

*********** Application info ***********

App name: Vigilante
Version code: 8
Version name: 1.0.9
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 22-02-2021 08:23:05
Last updated: 22-02-2021 08:23:05
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE
Default prefs: pref_dot = true, pref_bypass_dnd = false, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = MM.dd.yyyy HH:mm:ss, pref_notifications = true, pref_biometric_auth = false

*********** END of Application info ***********


^^^^^^^^^^^ Currently running foreground/background processes ^^^^^^^^^^^


com.crazylegend.vigilante.service.VigilanteService

^^^^^^^^^^^ END of running foreground/background processes info ^^^^^^^^^^^

**Comment by FunkyMuse** [comment]
Fixed in https://github.com/FunkyMuse/Vigilante/releases/tag/1.1.0
