### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by D1mka** [FunkyMuse/Vigilante#148]
----------- Stacktrace -----------

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 12027072 bytes
	at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:108)
	at i.s.m.g(Unknown Source:31)
	at com.crazylegend.vigilante.crashes.CrashFragment$c.a(:1)
	at d.a.f.a$a.onClick(:11)
	at android.view.View.performClick(View.java:7153)
	at android.view.View.performClickInternal(View.java:7126)
	at android.view.View.access$3500(View.java:806)
	at android.view.View$PerformClick.run(View.java:27713)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
Caused by: android.os.TransactionTooLargeException: data parcel size 12027072 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:510)
	at android.content.IClipboard$Stub$Proxy.setPrimaryClip(IClipboard.java:288)
	at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:106)
	... 14 more

----------- END of stacktrace -----------

``````````` Thread info ```````````

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 18
Thread time: 0 hr 1 min, 13 sec

``````````` END of thread info ```````````

----------- Device info -----------

Report ID: 89ff2b3b-9681-466a-8e7c-18307869ca76
Device ID: 093643b2096e49b4
Application version: 7
Default launcher: com.teslacoilsw.launcher
Timezone name: Восточная Европа, стандартное время
Timezone ID: Europe/Tallinn
Version release: 10
Version incremental : root.20200605.114948
Version SDK: 29
Board: s95v79c2k_gq_p_eea
Bootloader: unknown
Brand: Ulefone
CPU_ABIS_32: armeabi-v7a, armeabi
CPU_ABIS_64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: Armor_9
Display: Armor 9_TF1_EEA_V01
Fingerprint: Ulefone/Armor_9_EEA/Armor_9:10/QP1A.190711.020/root.20200605.114948:user/release-keys
Hardware: mt6779
Host: root
ID: QP1A.190711.020
Manufacturer: Ulefone
Product: Armor_9_EEA
Build time: 1591328309000
Build time formatted: 05-06-2020 06:38:29
Type: user
Radio: MOLY.LR13.R1.MP.V71.6.P1,MOLY.LR13.R1.MP.V71.6.P1
Tags: release-keys
User: root
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 39
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: MT6779V/CE
# of CPU cores: 8
Up time with sleep: 48 hr 41 min, 50 sec
Up time without sleep: 43 hr 8 min, 31 sec

----------- END of Device info -----------

########### Exit reasons ###########
N/A
########### END of exit reasons ###########

*********** Application info ***********

App name: Vigilante
Version code: 7
Version name: 1.0.8
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 14-01-2021 23:37:42
Last updated: 14-01-2021 23:37:42
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE
Default prefs: pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_notifications = true, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = true

*********** END of Application info ***********

^^^^^^^^^^^ Currently running foreground/background processes ^^^^^^^^^^^

com.crazylegend.vigilante.service.VigilanteService

^^^^^^^^^^^ END of running foreground/background processes info ^^^^^^^^^^^

**Comment by FunkyMuse** [comment]
Update to the latest version of the app please, it was fixed already.

**Comment by D1mka** [comment]
Sorry, thanks.)
