### ISSUE TITLE
Cannot uninstall app via Package Installer - Additional Information

### ISSUE THREAD

**Issue by kotx** [FunkyMuse/Vigilante#150]
There are three issues (#71, #122, #68) that already bring up this problem. There is an answer provided in #71, however I believe this may be resolvable by somehow obtaining a new UUID for the app. 

Seeing as it is troublesome (and sometimes not possible) for a user to connect to their phone via ADB or to enable debugging in the first place, it may be desirable to fix this soon. Not being able to uninstall an app could be seen as malicious. 

Even if this is an issue with Package Installer itself, it might be easier to resolve on your end. I couldn't find where to open an issue with Package Installer. 

<details open>
<summary><b>Crash report</b></summary>
<pre>
time: 1616305512322
msg: java.lang.IllegalArgumentException: Invalid UUID string: 029C-1903
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.packageinstaller/com.android.packageinstaller.UninstallerActivity}: java.lang.IllegalArgumentException: Invalid UUID string: 029C-1903
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: 029C-1903
	at java.util.UUID.fromString(UUID.java:194)
	at android.os.storage.StorageManager.convert(StorageManager.java:2290)
	at com.android.packageinstaller.handheld.UninstallAlertDialogFragment.getAppDataSizeForUser(UninstallAlertDialogFragment.java:78)
	at com.android.packageinstaller.handheld.UninstallAlertDialogFragment.getAppDataSize(UninstallAlertDialogFragment.java:114)
	at com.android.packageinstaller.handheld.UninstallAlertDialogFragment.onCreateDialog(UninstallAlertDialogFragment.java:179)
	at android.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:417)
	at android.app.Fragment.performGetLayoutInflater(Fragment.java:1351)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1303)
	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3057)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:184)
	at android.app.Activity.performCreate(Activity.java:7831)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more
</pre>
</details>

**Comment by FunkyMuse** [comment]
As you can clearly see from the log it's the package installer issue, I haven't been able to reproduce the issue, might be tied to certain devices only or people downloading it from F-droid, could be that the service is still running in the background and you can't uninstall at the moment.

Let's be clear about one thing, it's not malicious... let's not spread dirt on the app when the package installer from your ROM crashes, I have this tested few times and couldn't reproduce the issue with the following devices tried:
- LG V20, LG G5
- Xiaomi Mi5s, Mi 4c (running LoS)
- Pixel XL 2
- Huawei mate pro 20
- Asus Zenfone 5

To delete the app itself programatically, the app would need admin rights or root at least

Thanks for bringing that up, I'd look more into the issue when i have free time

**Comment by kotx** [comment]
If it helps, I'm running HavocOS 3.11 (Android 10) on a moto g8 power. So yeah, this 100% could be a ROM Package Installer issue. 

Stopping the service before uninstall doesn't seem to work. Uninstall still fails.

**Comment by Bdroid191** [comment]
I am also having issues Uninstaller this app (temporarily :) 
It says "package installer keeps stopping".  I am using Samsung Galaxy Tab A.  Unfortunately, I do have a stubborn Spyware issue right now and will have to throw this device out and start over with along with a 2nd internet connection used just by me.  Hope this helps somehow.

**Comment by FunkyMuse** [comment]
As you might have guessed, this issue isn't tied to the app, rather to the package manager that comes with the phone, it happens on heavily skinned phones, happened on my Xiaomi, Asus zenfone, but hasn't happened even at once on my Pixel 5 and XL 2,

**Comment by FunkyMuse** [comment]
Linked into the readme https://github.com/FunkyMuse/Vigilante/blob/master/README.md

**Comment by surfstian** [comment]
"Not being able to uninstall an app could be seen as malicious"

I have to agree. And this has been closed with no solution? Rooting of going highwire in commandline is not a liable option for users.

First time ever an app will not uninstall.  This is elementary, is this even acceptable in the F-Droid store?

At least put some sort of warning that this is an experimental app that can cause issues.
