### ISSUE TITLE
reporting crash

### ISSUE THREAD

**Issue by jacktlittlesparrow** [FunkyMuse/Vigilante#184]
`` Stacktrace ``

android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@a5fe1bb is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1101)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:409)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:118)
	at com.crazylegend.vigilante.service.VigilanteService.onServiceConnected(:10)
	at android.accessibilityservice.AccessibilityService.dispatchServiceConnected(AccessibilityService.java:728)
	at android.accessibilityservice.AccessibilityService.access$100(AccessibilityService.java:234)
	at android.accessibilityservice.AccessibilityService$2.onServiceConnected(AccessibilityService.java:2071)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:2312)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7776)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 11
Thread time: 0 hr 0 min, 0 sec

`` END of thread info ``

`` Device info ``

Report ID: a36c58b8-ff72-41a9-8daf-f0fe7e1e9784
Device ID: 6193ad35ac3960a8
Application version: 11
Default launcher: com.microsoft.launcher
Timezone name: Pacific Standard Time
Timezone ID: America/Los_Angeles
Version release: 11
Version incremental : 2C5X-0
Version SDK: 30
Board: trinket
Bootloader: unknown
Brand: T-Mobile
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: Porto
Display: RKQ1.201202.002 release-keys
Fingerprint: T-Mobile/5062W/Porto:11/RKQ1.201202.002/2C5X-0:user/release-keys
Hardware: qcom
Host: WS74930-slave
ID: RKQ1.201202.002
Manufacturer: TCL
Product: 5062W
Build time: 1616491397000
Build time formatted: 23-03-2021 02:23:17
Type: user
Radio: .1-00397-NICOBAR_GEN_PACK-2.379916.1.382574.2
Tags: release-keys
User: android-bld
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 51
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc TRINKET
Number of CPU cores: 8
Up time with sleep: 99 hr 45 min, 43 sec
Up time without sleep: 65 hr 21 min, 31 sec

`` END of Device info ``

`` Exit reasons ``

`` Exit reason #1 ``
Description: remove task
Importance: FOREGROUND_SERVICE
Reason: USER_REQUESTED
Timestamp: 25-04-2021 23:53:17
`` END of exit reason #1 ``

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 11
Version name: 1.1.2
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 25-04-2021 23:37:24
Last updated: 25-04-2021 23:37:24
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE
Default prefs: pref_dot = true, pref_bypass_dnd = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_notifications = true, pref_biometric_auth = true
Default prefs: pref_dot = true, pref_bypass_dnd = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_notifications = true, pref_biometric_auth = true

`` END of Application info ``

`` Currently running foreground/background processes ``

N/A

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
This is tied to OEMs badly implementing stuff, rarely happens.
