### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by shazgames** [FunkyMuse/Vigilante#196]
`` Stacktrace ``

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 6014536 bytes
	at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:107)
	at l.t.m.g(Unknown Source:31)
	at e.a.i.i.a.u(:2)
	at o.o.j.a.a.r(:2)
	at p.a.n0.run(Unknown Source:84)
	at p.a.t0.y(:2)
	at p.a.m2.g.a(:2)
	at e.d.a.i.i0(:1)
	at p.a.a.r0(:7)
	at e.d.a.i.V(:4)
	at l.p.m.j(Unknown Source:16)
	at com.crazylegend.vigilante.crashes.CrashFragment$e.a(:1)
	at e.a.f.b.onClick(:11)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28305)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.os.TransactionTooLargeException: data parcel size 6014536 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:550)
	at android.content.IClipboard$Stub$Proxy.setPrimaryClip(IClipboard.java:288)
	at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:105)
	... 23 more

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 17
Thread time: 0 hr 0 min, 1 sec

`` END of thread info ``

`` Device info ``

Report ID: 45a6ed7c-c129-488e-9ef7-01f552b21ee7
Device ID: 0af93a94a9d8eb18
Application version: 11
Default launcher: com.google.android.apps.nexuslauncher
Timezone name: Krasnoyarsk Standard Time
Timezone ID: Asia/Krasnoyarsk
Version release: 11
Version incremental : 1615898718
Version SDK: 30
Board: begonia
Bootloader: unknown
Brand: Redmi
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: begonia
Display: RQ2A.210305.006
Fingerprint: Redmi/begonia/begonia:11/RQ2A.210305.006/1245:userdebug/release-keys
Hardware: mt6785
Host: b439a03cf35d
ID: RQ2A.210305.006
Manufacturer: Xiaomi
Product: aosp_begonia
Build time: 1615898619000
Build time formatted: 16-03-2021 19:43:39
Type: user
Radio: MOLY.LR13.R1.TC8.SP.V2.P44,MOLY.LR13.R1.TC8.SP.V2.P44
Tags: release-keys
User: android_build
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 9
Battery remaining time: N/A
Is battery charging: No
Is device rooted: Yes
CPU Model: MT6785V/CC
Number of CPU cores: 8
Up time with sleep: 13 hr 42 min, 35 sec
Up time without sleep: 9 hr 28 min, 49 sec

`` END of Device info ``

`` Exit reasons ``

`` Exit reason #1 ``
Description: crash
Importance: FOREGROUND_SERVICE
Reason: CRASH
Timestamp: 07-05-2021 01:21:50
`` END of exit reason #1 ``

 `` Exit reason #2 ``
Description: crash
Importance: SERVICE
Reason: CRASH
Timestamp: 06-05-2021 11:40:03
`` END of exit reason #2 ``

 `` Exit reason #3 ``
Description: crash
Importance: SERVICE
Reason: CRASH
Timestamp: 04-05-2021 08:13:46
`` END of exit reason #3 ``

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 11
Version name: 1.1.2
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 17-04-2021 23:30:31
Last updated: 17-04-2021 23:34:11
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE
Default prefs: pref_dot = true, pref_bypass_dnd = false, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_notifications = true, pref_biometric_auth = true
Default prefs: pref_dot = true, pref_bypass_dnd = false, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_notifications = true, pref_biometric_auth = true

`` END of Application info ``

`` Currently running foreground/background processes ``

N/A

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
Update to 1.1.3
