### ISSUE TITLE
Crash when opening dot indicator cusomization

### ISSUE THREAD

**Issue by qwerty287** [FunkyMuse/Vigilante#229]
Hi,
The app crashes if I try to open the dot indicator customization. 
```
`` Stacktrace ``

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	... 1 more
Caused by: java.lang.NoSuchMethodException: c.a.i.k.b.fromBundle [class android.os.Bundle]
	at java.lang.Class.getMethod(Class.java:2072)
	at java.lang.Class.getMethod(Class.java:1693)
	at j.r.f.getValue(:3)
	at com.crazylegend.vigilante.customization.CustomizationFragment.y0(:1)
	at com.crazylegend.vigilante.customization.CustomizationFragment.f0(Unknown Source:5)
	at j.m.b.h0.f(:11)
	at j.m.b.h0.k(:8)
	at j.m.b.a0.B(:19)
	at j.m.b.a0.W(Unknown Source:91)
	at j.m.b.a0.z(:4)
	at j.m.b.a0$d.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	... 3 more


`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 16
Thread time: 0 hr 0 min, 3 sec

`` END of thread info ``

`` Device info ``

Report ID: 1d440d49-d33a-4be0-b663-79ff4241fe12
Device ID: d4345db334ca22b9
Application version: 13
Default launcher: ch.deletescape.lawnchair.plah
Timezone name: Mitteleuropäische Normalzeit
Timezone ID: Europe/Berlin
Version release: 10
Version incremental : 00WW_1_290_SP06
Version SDK: 29
Board: SM6125
Bootloader: unknown
Brand: Nokia
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: CAP_sprout
Display: 00WW_1_290_SP06
Fingerprint: Nokia/CaptainAmerica_00EEA/CAP_sprout:10/QKQ1.200114.002/00WW_1_29F:user/release-keys
Hardware: qcom
Host: sz-103.rnd.longcheer.net
ID: QKQ1.200114.002
Manufacturer: HMD Global
Product: CaptainAmerica_00EEA
Build time: 1619420410000
Build time formatted: 26-04-2021 09:00:10
Type: user
Radio: BAR_GEN_PACK-1.299035.1.312160.1,BAR_GEN_PACK-1.299035.1.312160.1
Tags: release-keys
User: jenkins
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 59
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc TRINKET
Number of CPU cores: 8
Up time with sleep: 8 hr 30 min, 29 sec
Up time without sleep: 2 hr 38 min, 0 sec

`` END of Device info ``

`` Exit reasons ``

N/A

`` END of exit reasons ``


`` Currently running foreground/background processes ``


com.crazylegend.vigilante.service.VigilanteService

`` END of running foreground/background processes info ``
```

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/issues/224
