### ISSUE TITLE
mokhtari571913@gmail.com

### ISSUE THREAD

**Issue by BrahimMokhtari** [FunkyMuse/Vigilante#252]
`` Stacktrace ``

java.lang.IllegalStateException: Fragment SplashFragment{8b6c3e2} (1b74579b-5eba-4938-b2cf-e87e569a6f79) has not been attached yet.
	at j.m.b.n.l(Unknown Source:17)
	at c.a.i.o.a.j.a(:6)
	at c.a.i.d0.g.onAnimationEnd(:5)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:978)
	at android.view.Choreographer.doCallbacks(Choreographer.java:804)
	at android.view.Choreographer.doFrame(Choreographer.java:735)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:264)
	at android.app.ActivityThread.main(ActivityThread.java:7663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 11
Thread time: 0 hr 0 min, 0 sec

`` END of thread info ``

`` Device info ``

Report ID: bee2bdd4-d2cc-45e0-9618-0b85f6ac0be0
Device ID: 386be9892a28b707
Application version: 14
Default launcher: com.transsion.XOSLauncher
Timezone name: GMT+00:00
Timezone ID: Africa/Casablanca
Version release: 10
Version incremental : GH-GL-210414V219
Version SDK: 29
Board: Infinix-X657C
Bootloader: unknown
Brand: Infinix
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: N/A
Supported ABIS: armeabi-v7a, armeabi
Device: Infinix-X657C
Display: X657C-H6117GH-QGo-GL-210414V219
Fingerprint: Infinix/X657C-GL/Infinix-X657C:10/QP1A.190711.020/GH-GL-210414V219:user/release-keys
Hardware: mt6761
Host: buildsrv-234
ID: QP1A.190711.020
Manufacturer: INFINIX MOBILITY LIMITED
Product: X657C-GL
Build time: 1618366069000
Build time formatted: 14-04-2021 02:07:49
Type: user
Radio: MOLY.LR12A.R3.MP.V114.9.P17
Tags: release-keys
User: buildsrv-ci
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: Yes
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_ALL_DISABLED_WHEN_SCREEN_OFF
Is device idle: No
Battery percentage: 68
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: MT6761V/WE
Revision	: 0000
Serial		: 0000000000000000
Number of CPU cores: 4
Up time with sleep: 0 hr 2 min, 38 sec
Up time without sleep: 0 hr 2 min, 38 sec

`` END of Device info ``

`` Exit reasons ``

N/A

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 14
Version name: 1.2.1
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 25-06-2021 15:26:20
Last updated: 25-06-2021 15:26:20
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: pref_exclude_vigilante_from_notifications = true, pref_delete_history = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = true
Default prefs: pref_exclude_vigilante_from_notifications = true, pref_delete_history = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = true

`` END of Application info ``

`` Currently running foreground/background processes ``

N/A

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
Update to 1.2.2
