### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by Kreuger** [FunkyMuse/Vigilante#272]
Hey man today I got a crash despite not using any app that accesses my camera or mic. I have location turned off as well so Im not sure what caused it.

```
FATAL EXCEPTION: main
Process: com.crazylegend.vigilante, PID: 5061
java.lang.StackOverflowError: stack size 8192KB
	at android.os.Parcel.obtain(Parcel.java:410)
	at android.os.BaseBundle.copyInternal(BaseBundle.java:435)
	at android.os.BaseBundle.<init>(BaseBundle.java:174)
	at android.os.Bundle.<init>(Bundle.java:149)
	at android.view.accessibility.AccessibilityNodeInfo.init(AccessibilityNodeInfo.java:3605)
	at android.view.accessibility.AccessibilityNodeInfo.<init>(AccessibilityNodeInfo.java:782)
	at android.view.accessibility.AccessibilityCache.getNode(AccessibilityCache.java:224)
	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:328)
	at android.view.accessibility.AccessibilityNodeInfo.getChild(AccessibilityNodeInfo.java:1002)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
	at com.crazylegend.vigilante.permissions.PermissionsProcessor.n(:4)
```

**Comment by FunkyMuse** [comment]
Thanks for reporting this, I'll look at it in the upcoming days.

**Comment by FunkyMuse** [comment]
It would be helpful if you go into crashes and copy paste the log here as well.

**Comment by Kreuger** [comment]
I was unaware that you had a built in crash reporting system. I cant open any older ones though. Oddly enough, they cause a crash. But I will try to remember next time.

**Comment by FunkyMuse** [comment]
> I was unaware that you had a built in crash reporting system. I cant open any older ones though. Oddly enough, they cause a crash. But I will try to remember next time.

The crash isn't detailed from what you've posted, that's why I will close the issue for now and I will be reopening it in the future when you add a crash log that is coming from the built in reported, sounds good?
