### ISSUE TITLE
App crashes when a video/audio stream abruptly ends.

### ISSUE THREAD

**Issue by gfish35** [FunkyMuse/Vigilante#437]
I was testing the app while using Telegram's video note feature which records both audio and video when used.
It worked well, I started recording, and the indicator appeared. But abruptly ended the recording BEFORE I gave Telegram time to load the actual camera feed. As soon as I ended it, the app crashed.

Maybe the daemon couldn't understand how a stream ended before it fully started?

Here is the crash report. Sorry for the mess.

`` Stacktrace ``

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.view.View.getTag()' on a null object reference
	at c6.f.s(Unknown Source:31)
	at u3.g.f(Unknown Source:11)
	at com.crazylegend.vigilante.service.VigilanteService$a.b(:2)
	at k3.a$a.q(:3)
	at q7.a.x(Unknown Source:8)
	at e8.m0.run(Unknown Source:86)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
	Suppressed: e8.k0: [u1{Cancelling}@7fa18a1, Dispatchers.Main]

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 5
Thread time: 0 hr 0 min, 0 sec

`` END of thread info ``

`` Device info ``

Report ID: 0f93aac4-5629-4b4c-a4ce-da81eb9eb392
Application version: 18
Default launcher: com.teslacoilsw.launcher
Timezone name: India Standard Time
Timezone ID: Asia/Kolkata
Version release: 8.0.0
Version incremental : 22
Version SDK: 26
Board: msm8953
Bootloader: 0xC0CD
Brand: motorola
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: N/A
Supported ABIS: armeabi-v7a, armeabi
Device: albus
Display: OPSS27.76-12-25-23
Fingerprint: motorola/albus/albus:8.0.0/OPSS27.76-12-25-23/22:user/release-keys
Hardware: qcom
Host: ilclbld31
ID: OPSS27.76-12-25-23
Manufacturer: motorola
Product: albus
Build time: 1560150415000
Build time formatted: 10-06-2019 12:36:55
Type: user
Radio: M8953P_50.59.07.96R ALBUS_INDIADSDS_CUST
Tags: release-keys
User: hudsoncm
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: Yes
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: N/A
Location power save mode: N/A
Is device idle: No
Battery percentage: 51
Battery remaining time: N/A
Is battery charging: No
Is device rooted: Yes
CPU Model: Qualcomm Technologies, Inc MSM8953
Revision	: 8400
Processor	: ARMv7 Processor rev 4 (v7l)
Device		: albus
Radio		: India
MSM Hardware	: MSM8953
Number of CPU cores: 8
Up time with sleep: 27 hr 31 min, 38 sec
Up time without sleep: 11 hr 31 min, 45 sec

`` END of Device info ``

`` Exit reasons ``

N/A

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 18
Version name: 1.2.5
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 10-05-2022 02:09:32
Last updated: 10-05-2022 02:09:32
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: camera_pref_notifications = true, pref_log_notifications = true, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = true, pref_log_empty_notifications = true, pref_log_lockscreen = true, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = true, pref_biometric_auth = false, location_pref_bypass_dnd = false, mic_pref_dot = true, pref_log_permissions = true, pref_log_headset = true, camera_pref_sound = true, camera_pref_bypass_dnd = false, mic_pref_notifications = true, pref_language = en, mic_pref_sound = false, pref_log_power = true
Default prefs: camera_pref_notifications = true, pref_log_notifications = true, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = true, pref_log_empty_notifications = true, pref_log_lockscreen = true, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = true, pref_biometric_auth = false, location_pref_bypass_dnd = false, mic_pref_dot = true, pref_log_permissions = true, pref_log_headset = true, camera_pref_sound = true, camera_pref_bypass_dnd = false, mic_pref_notifications = true, pref_language = en, mic_pref_sound = false, pref_log_power = true

`` END of Application info ``

`` Currently running foreground/background processes ``

com.crazylegend.vigilante.service.VigilanteService

`` END of running foreground/background processes info ``

Thanks for your kind attention.

**Comment by FunkyMuse** [comment]
I can't reproduce it on my Pixel 6 pro, can you maybe record a video?

**Comment by gfish35** [comment]
@FunkyMuse  Thanks for the quick reply.

Here is a recording of the crash.

https://user-images.githubusercontent.com/59993175/167579391-55e531ce-263a-4dcc-b64d-3f89719b8c61.mp4

Hope this helps reproduce the same crash on your device.
Thank You.

**Comment by FunkyMuse** [comment]
Thanks this helps, will try to reproduce and fix it
