### ISSUE TITLE
Crashed when trying to enable biometrics in settings

### ISSUE THREAD

**Issue by jonapoul** [FunkyMuse/Vigilante#46]
----------- Stacktrace -----------

java.lang.SecurityException: Must have USE_BIOMETRIC permission: Neither user 10635 nor current process has android.permission.USE_BIOMETRIC.
	at android.os.Parcel.createException(Parcel.java:2071)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.hardware.biometrics.IBiometricService$Stub$Proxy.authenticate(IBiometricService.java:338)
	at android.hardware.biometrics.BiometricPrompt.authenticateInternal(BiometricPrompt.java:652)
	at android.hardware.biometrics.BiometricPrompt.authenticate(BiometricPrompt.java:619)
	at i.d.e.P0(:63)
	at d.a.i.l.a.n.a(:33)
	at d.a.i.x.e.a(:1)
	at androidx.preference.Preference.b(Unknown Source:4)
	at androidx.preference.TwoStatePreference.x(:2)
	at androidx.preference.Preference.H(:3)
	at androidx.preference.SwitchPreferenceCompat.H(Unknown Source:0)
	at androidx.preference.Preference$a.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7201)
	at android.view.View.performClickInternal(View.java:7170)
	at android.view.View.access$3500(View.java:806)
	at android.view.View$PerformClick.run(View.java:27562)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:1930)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1958)
	at com.android.server.biometrics.BiometricService.checkPermission(BiometricService.java:845)
	at com.android.server.biometrics.BiometricService.access$1700(BiometricService.java:86)
	at com.android.server.biometrics.BiometricService$BiometricServiceWrapper.authenticate(BiometricService.java:648)

----------- END of stacktrace -----------

``````````` Thread info ```````````

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 13
Thread time: 0 hr 0 min, 6 sec

``````````` END of thread info ```````````

----------- Device info -----------

Report ID: e7d3f058-589d-4825-8448-6512243740ff
Device ID: ce549d75996a3cf5
Application version: 5
Default launcher: com.teslacoilsw.launcher
Timezone name: Greenwich Mean Time
Timezone ID: Europe/London
Version release: 10
Version incremental : 2011161919
Version SDK: 29
Board: sdm845
Bootloader: unknown
Brand: OnePlus
CPU_ABIS_32: armeabi-v7a, armeabi
CPU_ABIS_64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: OnePlus6
Display: ONEPLUS A6003_22_201116
Fingerprint: OnePlus/OnePlus6/OnePlus6:10/QKQ1.190716.003/2011161919:user/release-keys
Hardware: qcom
Host: rd-build-72
ID: QKQ1.190716.003
Manufacturer: OnePlus
Product: OnePlus6
Build time: 1605526159000
Build time formatted: 16-11-2020 11:29:19
Type: user
Radio: 845_GEN_PACK-1.276740.1.331501.2
Tags: release-keys
User: jenkins
User IDs: N/A
Is sustained performance mode supported: Yes
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 93
Battery remaining time: 01-01-1970 01:09:34
Is battery charging: Yes
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc SDM845
# of CPU cores: 8
Up time with sleep: 322 hr 49 min, 56 sec
Up time without sleep: 202 hr 2 min, 43 sec

----------- END of Device info -----------

########### Exit reasons ###########
N/A
########### END of exit reasons ###########

*********** Application info ***********

App name: Vigilante
Version code: 5
Version name: 1.0.6
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: 80TIH8ebytS8JEoC2hG/5fpUBHo=
Is debuggable: No
First installed: 19-12-2020 21:50:27
Last updated: 19-12-2020 21:50:27
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.VIBRATE
Default prefs: pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_notifications = true, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = false

*********** END of Application info ***********

^^^^^^^^^^^ Currently running foreground/background processes ^^^^^^^^^^^

N/A

^^^^^^^^^^^ END of running foreground/background processes info ^^^^^^^^^^^

**Comment by jonapoul** [comment]
Let me know if you need any more info!

**Comment by FunkyMuse** [comment]
> Let me know if you need any more info!

Do you have any other device to test this on?
I can't replicate this issue.

**Comment by Flouzr** [comment]
So I upgraded from the previous version of Vigilante to the current. I had biometrics enabled and am crashing as well.

`FATAL EXCEPTION: main
Process: com.crazylegend.vigilante, PID: 23939
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.crazylegend.vigilante/com.crazylegend.vigilante.activities.MainActivity}: java.lang.RuntimeException: Failed to call observer method
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.RuntimeException: Failed to call observer method
	at i.o.c$a.a(:1)
	at androidx.lifecycle.ReflectiveGenericLifecycleObserver.l(:1)
	at i.o.s$a.a(Unknown Source:14)
	at i.o.s.j(:27)
	at i.o.s.g(Unknown Source:19)
	at i.o.d0.a(:3)
	at i.o.d0$b.onActivityPostCreated(Unknown Source:2)
	at android.app.Activity.dispatchActivityPostCreated(Activity.java:1330)
	at android.app.Activity.performCreate(Activity.java:8010)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
	... 11 more
Caused by: android.view.InflateException: Binary XML file line #18 in com.crazylegend.vigilante:layout/activity_main: Binary XML file line #18 in com.crazylegend.vigilante:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: android.view.InflateException: Binary XML file line #18 in com.crazylegend.vigilante:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: java.lang.SecurityException: Must have USE_BIOMETRIC permission: Neither user 10356 nor current process has android.permission.USE_BIOMETRIC.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.hardware.biometrics.IAuthService$Stub$Proxy.canAuthenticate(IAuthService.java:344)
	at android.hardware.biometrics.BiometricManager.canAuthenticate(BiometricManager.java:248)
	at android.hardware.biometrics.BiometricManager.canAuthenticate(BiometricManager.java:236)
	at i.d.p.a(:1)
	at d.a.i.l.a.n.<init>(:3)
	at d.a.i.c.a$c$b$b.u(:2)
	at d.a.i.c.a$c$b$b.j(:8)
	at d.a.i.y.a.I0(:3)
	at d.a.i.y.a.P(:2)
	at i.l.b.m.Q(:2)
	at d.a.i.y.a.Q(Unknown Source:0)
	at i.l.b.j0.c(:7)
	at i.l.b.j0.k(:8)
	at i.l.b.c0.E(:8)
	at i.l.b.c0.Z(Unknown Source:94)
	at i.l.b.c0.C(:4)
	at i.l.b.c0.w(:3)
	at i.l.b.c0.m(:2)
	at i.l.b.m.T(:4)
	at androidx.navigation.fragment.NavHostFragment.T(:34)
	at i.l.b.j0.e(:1)
	at i.l.b.j0.k(:8)
	at i.l.b.c0.E(:8)
	at i.l.b.c0.Z(Unknown Source:94)
	at i.l.b.c0.D(Unknown Source:30)
	at androidx.fragment.app.FragmentContainerView.<init>(:7)
	at i.l.b.a0.onCreateView(Unknown Source:16)
	at i.l.b.p.onCreateView(:4)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1067)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)`
