### ISSUE TITLE
Ел

### ISSUE THREAD

**Issue by toha18031992** [FunkyMuse/Vigilante#496]

**Comment by toha18031992** [comment]
`` Stacktrace ``

java.lang.IllegalArgumentException: MetricAffectingSpan can not be set to PrecomputedText.
	at android.text.PrecomputedText.setSpan(PrecomputedText.java:649)
	at androidx.emoji2.text.d.i(SourceFile:14)
	at a1.d.filter(SourceFile:1)
	at android.widget.TextView.setText(TextView.java:6289)
	at android.widget.TextView.setText(TextView.java:6253)
	at android.widget.TextView.setText(TextView.java:6197)
	at v0.k.e(SourceFile:2)
	at androidx.appcompat.widget.c0.onMeasure(SourceFile:1)
	at android.view.View.measure(View.java:25161)
	at androidx.constraintlayout.widget.ConstraintLayout$b.b(SourceFile:23)
	at x.f.i0(SourceFile:11)
	at y.i.b(SourceFile:2)
	at y.i.d(SourceFile:8)
	at y.i.b(SourceFile:30)
	at y.i.b(SourceFile:16)
	at x.f.Y(SourceFile:20)
	at y.b.b(SourceFile:5)
	at androidx.constraintlayout.widget.ConstraintLayout.q(SourceFile:55)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(SourceFile:12)
	at android.view.View.measure(View.java:25161)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at t.a.onMeasure(Unknown Source:76)
	at com.google.android.material.card.MaterialCardView.onMeasure(Unknown Source:0)
	at android.view.View.measure(View.java:25161)
	at androidx.recyclerview.widget.LinearLayoutManager.d1(SourceFile:11)
	at androidx.recyclerview.widget.LinearLayoutManager.Q0(SourceFile:2)
	at androidx.recyclerview.widget.LinearLayoutManager.i1(Unknown Source:34)
	at androidx.recyclerview.widget.LinearLayoutManager.w0(Unknown Source:6)
	at androidx.recyclerview.widget.RecyclerView.e0(SourceFile:2)
	at androidx.recyclerview.widget.RecyclerView$z.run(Unknown Source:103)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
	at android.view.Choreographer.doFrame(Choreographer.java:907)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)


`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 1
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 27
Thread time: 0 hr 1 min, 16 sec

`` END of thread info ``

`` Device info ``

Report ID: 4dfadcf1-8a17-45bd-a7ef-8513c73ce321
Device ID: 9e767807b97c2706
Application version: 19
Default launcher: com.huawei.android.launcher
Timezone name: Восточная Европа, стандартное время
Timezone ID: Europe/Kiev
Version release: 10
Version incremental : 10.0.0.208C432
Version SDK: 29
Board: STK-L21
Bootloader: unknown
Brand: HUAWEI
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: HWSTK-HF
Display: STK-L21 10.0.0.208(C432E8R1P2)
Fingerprint: HUAWEI/STK-L21/HWSTK-HF:10/HUAWEISTK-LX1/10.0.0.208C432:user/release-keys
Hardware: kirin710
Host: cn-central-1b-43147a7441596078945615-3091104888-2f3vm
ID: HUAWEISTK-LX1
Manufacturer: HUAWEI
Product: STK-L21
Build time: 1596082650000
Build time formatted: 30-07-2020 07:17:30
Type: user
Radio: 21C20B388S000C000,21C20B388S000C000
Tags: release-keys
User: test
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 28
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: vendor Kirin710
Number of CPU cores: 8
Up time with sleep: 1 hr 47 min, 28 sec
Up time without sleep: 1 hr 47 min, 28 sec

`` END of Device info ``

`` Exit reasons ``

N/A

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 19
Version name: 1.2.6
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: 80TIH8ebytS8JEoC2hG/5fpUBHo=
Is debuggable: No
First installed: 08-08-2022 13:58:14
Last updated: 08-08-2022 13:58:14
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: camera_pref_notifications = true, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = ru, location_pref_notifications = true, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = true, location_pref_bypass_dnd = false, mic_pref_dot = true, camera_pref_sound = true, pref_delete_history = false, camera_pref_bypass_dnd = false, mic_pref_notifications = true, pref_language = ru, mic_pref_sound = true
Default prefs: camera_pref_notifications = true, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = ru, location_pref_notifications = true, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = true, location_pref_bypass_dnd = false, mic_pref_dot = true, camera_pref_sound = true, pref_delete_history = false, camera_pref_bypass_dnd = false, mic_pref_notifications = true, pref_language = ru, mic_pref_sound = true

`` END of Application info ``


`` Currently running foreground/background processes ``


com.crazylegend.vigilante.service.VigilanteService

`` END of running foreground/background processes info ``
