### ISSUE TITLE
App fails to request biometric permission

### ISSUE THREAD

**Issue by Draftmission** [FunkyMuse/Vigilante#51]
Just installed the app, seems awesome. However, the option to enable biometric lock makes the app crash. Error log included below.

----------- Stacktrace -----------

java.lang.SecurityException: Must have USE_BIOMETRIC permission: Neither user 10749 nor current process has android.permission.USE_BIOMETRIC.
	at android.os.Parcel.createException(Parcel.java:2071)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.hardware.biometrics.IBiometricService$Stub$Proxy.authenticate(IBiometricService.java:338)
	at android.hardware.biometrics.BiometricPrompt.authenticateInternal(BiometricPrompt.java:652)
	at android.hardware.biometrics.BiometricPrompt.authenticate(BiometricPrompt.java:619)
	at i.d.e.P0(:63)
	at d.a.i.l.a.n.a(:33)
	at d.a.i.x.e.a(:1)
	at androidx.preference.Preference.b(Unknown Source:4)
	at androidx.preference.TwoStatePreference.x(:2)
	at androidx.preference.Preference.H(:3)
	at androidx.preference.SwitchPreferenceCompat.H(Unknown Source:0)
	at androidx.preference.Preference$a.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7201)
	at android.view.View.performClickInternal(View.java:7170)
	at android.view.View.access$3500(View.java:806)
	at android.view.View$PerformClick.run(View.java:27562)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:1930)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1958)
	at com.android.server.biometrics.BiometricService.checkPermission(BiometricService.java:845)
	at com.android.server.biometrics.BiometricService.access$1700(BiometricService.java:86)
	at com.android.server.biometrics.BiometricService$BiometricServiceWrapper.authenticate(BiometricService.java:648)

----------- END of stacktrace -----------

``````````` Thread info ```````````

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 8
Thread time: 0 hr 0 min, 0 sec

``````````` END of thread info ```````````

----------- Device info -----------

Report ID: 43a70d32-41d1-486a-83aa-2b70c7ab7170
Device ID: b6605dcd2303368e
Application version: 4
Default launcher: net.oneplus.launcher
Timezone name: Central European Standard Time
Timezone ID: Europe/Stockholm
Version release: 10
Version incremental : 2010292059
Version SDK: 29
Board: msm8998
Bootloader: unknown
Brand: OnePlus
CPU_ABIS_32: armeabi-v7a, armeabi
CPU_ABIS_64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: OnePlus5
Display: ONEPLUS A5000_23_201029
Fingerprint: OnePlus/OnePlus5/OnePlus5:10/QKQ1.191014.012/2010292059:user/release-keys
Hardware: qcom
Host: rd-build-104
ID: QKQ1.191014.012
Manufacturer: OnePlus
Product: OnePlus5
Build time: 1603977245000
Build time formatted: 29-10-2020 14:14:05
Type: user
Radio: MPSS.AT.2.0.c4.7-00070-8998_GEN_PACK-2.271073.1.277412.1
Tags: release-keys
User: jenkins
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 86
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc MSM8998
# of CPU cores: 8
Up time with sleep: 164 hr 8 min, 40 sec
Up time without sleep: 129 hr 9 min, 20 sec

----------- END of Device info -----------

########### Exit reasons ###########
N/A
########### END of exit reasons ###########

*********** Application info ***********

App name: Vigilante
Version code: 4
Version name: 1.0.5
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 22-12-2020 13:38:35
Last updated: 22-12-2020 13:38:35
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.VIBRATE
Default prefs: pref_dot = true, pref_exclude_vigilante_from_notifications = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_notifications = true, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = false

*********** END of Application info ***********

^^^^^^^^^^^ Currently running foreground/background processes ^^^^^^^^^^^

N/A

^^^^^^^^^^^ END of running foreground/background processes info ^^^^^^^^^^^

**Comment by FunkyMuse** [comment]
Hi buddy,

You're running 1.0.5

The latest release of the app is 1.0.7

**Comment by Draftmission** [comment]
Okay, thx
