### ISSUE TITLE
Crashed when Camera App uses camera and location at the same time

### ISSUE THREAD

**Issue by 5WhiteTiger5** [FunkyMuse/Vigilante#524]
`` Stacktrace ``

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.view.View.getTag()' on a null object reference
	at androidx.activity.l.n(Unknown Source:26)
	at w3.h.f(Unknown Source:11)
	at m3.a$a.r(SourceFile:7)
	at s7.a.v(Unknown Source:8)
	at g8.l0.run(Unknown Source:86)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)
	Suppressed: g8.j0: [u1{Cancelling}@24aff3a, Dispatchers.Main]

`` END of stacktrace ``

`` Thread info ``

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 15
Thread time: 0 hr 7 min, 4 sec

`` END of thread info ``

`` Device info ``

Report ID: 10aacb1a-e221-4671-bb8b-882fbe402ffd
Device ID: b8417bd18c56d787
Application version: 19
Default launcher: com.lge.launcher3
Timezone name: Central European Standard Time
Timezone ID: Europe/Berlin
Version release: 8.1.0
Version incremental : 1900915012697.FGN
Version SDK: 27
Board: mt6755
Bootloader: unknown
Brand: lge
CPU ABIS 32: armeabi-v7a, armeabi
CPU ABIS 64: N/A
Supported ABIS: armeabi-v7a, armeabi
Device: mcv5a
Display: O11019
Fingerprint: lge/mcv5a_lao_com/mcv5a:8.1.0/O11019/1900915012697.FGN:user/release-keys
Hardware: mcv5a
Host: LGEACI8R12
ID: O11019
Manufacturer: LGE
Product: mcv5a_lao_com
Build time: 1547013718000
Build time formatted: 09-01-2019 07:01:58
Type: user
Radio: MOLY.LR11.W1552.MD.TC01.CVLV.SP.V1.P16.T7, 2019/01/09 14:58
Tags: release-keys
User: jenkins
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: Yes
Is in interactive state: Yes
Is ignoring battery optimizations: No
Thermal status: N/A
Location power save mode: N/A
Is device idle: No
Battery percentage: 30
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: MT6750V/WS
Revision	: 0000
Serial		: 0000000000000000
Number of CPU cores: 8
Up time with sleep: 215 hr 39 min, 11 sec
Up time without sleep: 80 hr 55 min, 50 sec

`` END of Device info ``

`` Exit reasons ``

N/A

`` END of exit reasons ``

`` Application info ``

App name: Vigilante
Version code: 19
Version name: 1.2.6
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 16-10-2022 07:01:40
Last updated: 16-10-2022 07:01:40
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE, android.permission.WAKE_LOCK
Default prefs: camera_pref_notifications = true, pref_log_notifications = true, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = true, pref_log_empty_notifications = true, pref_log_lockscreen = false, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = true, pref_biometric_auth = true, location_pref_bypass_dnd = false, mic_pref_dot = true, pref_log_permissions = false, pref_log_headset = false, camera_pref_sound = true, camera_pref_bypass_dnd = false, mic_pref_notifications = true, pref_language = en, mic_pref_sound = true, pref_log_power = false
Default prefs: camera_pref_notifications = true, pref_log_notifications = true, mic_pref_bypass_dnd = false, location_pref_dot = true, camera_pref_dot = true, Locale.Helper.Selected.Language = en, location_pref_notifications = true, pref_log_empty_notifications = true, pref_log_lockscreen = false, pref_date = dd.MM.yyyy HH:mm:ss, location_pref_sound = true, pref_biometric_auth = true, location_pref_bypass_dnd = false, mic_pref_dot = true, pref_log_permissions = false, pref_log_headset = false, camera_pref_sound = true, camera_pref_bypass_dnd = false, mic_pref_notifications = true, pref_language = en, mic_pref_sound = true, pref_log_power = false

`` END of Application info ``

`` Currently running foreground/background processes ``

com.crazylegend.vigilante.service.VigilanteService

`` END of running foreground/background processes info ``

**Comment by FunkyMuse** [comment]
Does it always happen?

**Comment by 5WhiteTiger5** [comment]
The Access Dots dont appear and when I open the App(Access Dots) it crashes

**Comment by FunkyMuse** [comment]
so you're opening two apps that do the same thing and it crashes?

**Comment by 5WhiteTiger5** [comment]
1. my camera app used location and camera at the same time --> 2 dots appear in the top center of the screen.
2. app crashes and dots disappear
3. when I open the Vigiltante app, nothing happens when I click 'Turn On'.

**Comment by FunkyMuse** [comment]
> 1. my camera app used location and camera at the same time --> 2 dots appear in the top center of the screen.
> 
>     2. app crashes and dots disappear
> 
>     3. when I open the Vigiltante app, nothing happens when I click 'Turn On'.

Thanks, I'll look into that
