### ISSUE TITLE
App crashes when trying to set biometric authentication 

### ISSUE THREAD

**Issue by AlfredEVOL** [FunkyMuse/Vigilante#53]
Device: Samsung A50

Crash report
`----------- Stacktrace -----------

java.lang.SecurityException: Must have USE_BIOMETRIC permission: Neither user 10574 nor current process has android.permission.USE_BIOMETRIC.
	at android.os.Parcel.createException(Parcel.java:2088)
	at android.os.Parcel.readException(Parcel.java:2056)
	at android.os.Parcel.readException(Parcel.java:2004)
	at android.hardware.biometrics.IBiometricService$Stub$Proxy.authenticate(IBiometricService.java:383)
	at android.hardware.biometrics.BiometricPrompt.authenticateInternal(BiometricPrompt.java:958)
	at android.hardware.biometrics.BiometricPrompt.authenticate(BiometricPrompt.java:920)
	at i.d.e.P0(:63)
	at d.a.i.l.a.n.a(:33)
	at d.a.i.x.e.a(:1)
	at androidx.preference.Preference.b(Unknown Source:4)
	at androidx.preference.TwoStatePreference.x(:2)
	at androidx.preference.Preference.H(:3)
	at androidx.preference.SwitchPreferenceCompat.H(Unknown Source:0)
	at androidx.preference.Preference$a.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7870)
	at android.view.View.performClickInternal(View.java:7839)
	at android.view.View.access$3600(View.java:886)
	at android.view.View$PerformClick.run(View.java:29363)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7814)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2001)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2029)
	at com.android.server.biometrics.BiometricService.checkPermission(BiometricService.java:1082)
	at com.android.server.biometrics.BiometricService.access$1800(BiometricService.java:99)
	at com.android.server.biometrics.BiometricService$BiometricServiceWrapper.authenticate(BiometricService.java:804)

----------- END of stacktrace -----------

``````````` Thread info ```````````

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 18
Thread time: 0 hr 0 min, 9 sec

``````````` END of thread info ```````````

----------- Device info -----------

Report ID: d8b4dcd3-9619-4b0c-8c72-6f7ed1906d2a
Device ID: 38693c333c04063f
Application version: 4
Default launcher: com.sec.android.app.launcher
Timezone name: India Standard Time
Timezone ID: Asia/Kolkata
Version release: 10
Version incremental : A505FDDS5BTK3
Version SDK: 29
Board: exynos9610
Bootloader: A505FDDS5BTK3
Brand: samsung
CPU_ABIS_32: armeabi-v7a, armeabi
CPU_ABIS_64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: a50
Display: QP1A.190711.020.A505FDDS5BTK3
Fingerprint: samsung/a50dd/a50:10/QP1A.190711.020/A505FDDS5BTK3:user/release-keys
Hardware: exynos9610
Host: SWDH2809
ID: QP1A.190711.020
Manufacturer: samsung
Product: a50dd
Build time: 1605151837000
Build time formatted: 12-11-2020 09:00:37
Type: user
Radio: A505FXXS5BTIB,A505FXXS5BTIB
Tags: release-keys
User: dpi
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: Yes
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_GPS_DISABLED_WHEN_SCREEN_OFF
Is device idle: No
Battery percentage: 19
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: N/A
# of CPU cores: 8
Up time with sleep: 167 hr 15 min, 44 sec
Up time without sleep: 114 hr 13 min, 11 sec

----------- END of Device info -----------

########### Exit reasons ###########
N/A
########### END of exit reasons ###########

*********** Application info ***********

App name: Vigilante
Version code: 4
Version name: 1.0.5
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 23-12-2020 02:45:51
Last updated: 23-12-2020 02:45:51
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.VIBRATE
Default prefs: pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_notifications = true, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = false

*********** END of Application info ***********

^^^^^^^^^^^ Currently running foreground/background processes ^^^^^^^^^^^

com.crazylegend.vigilante.service.VigilanteService

^^^^^^^^^^^ END of running foreground/background processes info ^^^^^^^^^^^`

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/Vigilante/issues/51
