### ISSUE TITLE
crash report 3

### ISSUE THREAD

**Issue by TeTaniwha** [FunkyMuse/Vigilante#95]
----------- Stacktrace -----------

android.content.pm.PackageManager$NameNotFoundException: com.whatsapp
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:441)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:422)
	at d.a.a.b.a.a(Unknown Source:15)
	at com.crazylegend.vigilante.notifications.details.NotificationDetailsFragment$d$a.t(:17)
	at com.crazylegend.vigilante.notifications.details.NotificationDetailsFragment$d$a.l(:2)
	at g.a.m2.t.t(Unknown Source:59)
	at g.a.m2.t.k(:2)
	at g.a.m2.t0.j$a$a$b.t(:2)
	at g.a.m2.t0.j$a$a$b.l(:2)
	at g.a.b.s0(:5)
	at d.d.a.i.X(:2)
	at g.a.m2.t0.j$a$a.a(Unknown Source:121)
	at g.a.m2.o0.c(:15)
	at g.a.m2.o0$a.t(Unknown Source:12)
	at l.o.j.a.a.s(:2)
	at d.d.a.i.i0(Unknown Source:40)
	at g.a.k.q(:6)
	at g.a.k.y(Unknown Source:30)
	at g.a.k.s(:3)
	at g.a.m2.o0.e(:7)
	at g.a.m2.o0.a(:1)
	at g.a.m2.t0.s$a.k(:1)
	at g.a.m2.t0.r.v(:22)
	at g.a.m2.t0.r.a(Unknown Source:0)
	at d.a.e.b.a.t(:3)
	at l.o.j.a.a.s(:2)
	at g.a.o0.run(Unknown Source:72)
	at android.os.Handler.handleCallback(Handler.java:899)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:998)

----------- END of stacktrace -----------

``````````` Thread info ```````````

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 16
Thread time: 0 hr 0 min, 1 sec

``````````` END of thread info ```````````

----------- Device info -----------

Report ID: a6c534aa-3890-4c85-8281-da03d76bbc5d
Device ID: 3c644d12cb336a32
Application version: 6
Default launcher: com.oppo.launcher
Timezone name: New Zealand Standard Time
Timezone ID: Pacific/Auckland
Version release: 10
Version incremental : 1603175700
Version SDK: 29
Board: trinket
Bootloader: unknown
Brand: OPPO
CPU_ABIS_32: armeabi-v7a, armeabi
CPU_ABIS_64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: OP4B80L1
Display: CPH1941EX_11_C.81
Fingerprint: OPPO/CPH1941/OP4B80L1:10/QKQ1.200209.002/1603175700:user/release-keys
Hardware: qcom
Host: cp-ubuntu-28-198
ID: QKQ1.200209.002
Manufacturer: OPPO
Product: CPH1941
Build time: 1606123581000
Build time formatted: 23-11-2020 22:26:21
Type: user
Radio: Q_V1_P14,Q_V1_P14
Tags: release-keys
User: root
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: Yes
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 49
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc SDM665
# of CPU cores: 8
Up time with sleep: 4 hr 1 min, 40 sec
Up time without sleep: 4 hr 1 min, 40 sec

----------- END of Device info -----------

########### Exit reasons ###########
N/A
########### END of exit reasons ###########

*********** Application info ***********

App name: Vigilante
Version code: 6
Version name: 1.0.7
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 01-01-2021 14:46:54
Last updated: 01-01-2021 14:46:54
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE
Default prefs: Locale.Helper.Selected.Language = en

*********** END of Application info ***********

^^^^^^^^^^^ Currently running foreground/background processes ^^^^^^^^^^^

com.crazylegend.vigilante.service.VigilanteService

^^^^^^^^^^^ END of running foreground/background processes info ^^^^^^^^^^^

**Comment by TeTaniwha** [comment]
----------- Stacktrace -----------

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 11509184 bytes
	at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:108)
	at i.s.m.g(Unknown Source:31)
	at com.crazylegend.vigilante.crashes.CrashFragment$c.a(:1)
	at d.a.f.a$a.onClick(:11)
	at android.view.View.performClick(View.java:7394)
	at android.view.View.performClickInternal(View.java:7348)
	at android.view.View.access$3900(View.java:827)
	at android.view.View$PerformClick.run(View.java:28293)
	at android.os.Handler.handleCallback(Handler.java:899)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:998)
Caused by: android.os.TransactionTooLargeException: data parcel size 11509184 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:524)
	at android.content.IClipboard$Stub$Proxy.setPrimaryClip(IClipboard.java:288)
	at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:106)
	... 14 more


----------- END of stacktrace -----------

``````````` Thread info ```````````

Name: main
ID: 2
State: RUNNABLE
Priority: 5
Thread group name: main
Thread group parent: system
Thread group active count: 25
Thread time: 0 hr 1 min, 52 sec

``````````` END of thread info ```````````

----------- Device info -----------

Report ID: 8a5aa8e9-3d78-4d8a-89f2-d2c26459fcef
Device ID: 3c644d12cb336a32
Application version: 7
Default launcher: com.oppo.launcher
Timezone name: New Zealand Standard Time
Timezone ID: Pacific/Auckland
Version release: 10
Version incremental : 1603175700
Version SDK: 29
Board: trinket
Bootloader: unknown
Brand: OPPO
CPU_ABIS_32: armeabi-v7a, armeabi
CPU_ABIS_64: arm64-v8a
Supported ABIS: arm64-v8a, armeabi-v7a, armeabi
Device: OP4B80L1
Display: CPH1941EX_11_C.81
Fingerprint: OPPO/CPH1941/OP4B80L1:10/QKQ1.200209.002/1603175700:user/release-keys
Hardware: qcom
Host: cp-ubuntu-28-198
ID: QKQ1.200209.002
Manufacturer: OPPO
Product: CPH1941
Build time: 1606123581000
Build time formatted: 23-11-2020 22:26:21
Type: user
Radio: Q_V1_P14,Q_V1_P14
Tags: release-keys
User: root
User IDs: N/A
Is sustained performance mode supported: No
Is in power save mode: No
Is in interactive state: Yes
Is ignoring battery optimizations: No
Thermal status: STATUS_NONE
Location power save mode: MODE_NO_CHANGE
Is device idle: No
Battery percentage: 91
Battery remaining time: N/A
Is battery charging: No
Is device rooted: No
CPU Model: Qualcomm Technologies, Inc SDM665
# of CPU cores: 8
Up time with sleep: 4 hr 21 min, 8 sec
Up time without sleep: 4 hr 21 min, 8 sec

----------- END of Device info -----------

########### Exit reasons ###########
N/A
########### END of exit reasons ###########

*********** Application info ***********

App name: Vigilante
Version code: 7
Version name: 1.0.8
Package name: com.crazylegend.vigilante
Short package name: app
Flavor: N/A
Signatures: cBeZz38Z2v/AXmsKrs78iK04C74=
Is debuggable: No
First installed: 01-01-2021 14:46:54
Last updated: 01-01-2021 15:59:42
Requested permissions: android.permission.FOREGROUND_SERVICE, android.permission.RECEIVE_BOOT_COMPLETED, android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, android.permission.USE_BIOMETRIC, android.permission.USE_FINGERPRINT, android.permission.VIBRATE
Default prefs: pref_dot = true, Locale.Helper.Selected.Language = en, pref_language = en, pref_notifications = true, pref_date = dd.MM.yyyy HH:mm:ss, pref_biometric_auth = false

*********** END of Application info ***********


^^^^^^^^^^^ Currently running foreground/background processes ^^^^^^^^^^^


com.crazylegend.vigilante.service.VigilanteService

^^^^^^^^^^^ END of running foreground/background processes info ^^^^^^^^^^^
